# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ds3c-ctf-team
google_analytics: ds3c-ctf-team
title: ds3c-ctf-team

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ds3c-ctf-team

description: ds3c-ctf-team
author:
  name: ds3c-ctf-team
  email: ds3c-ctf-team@gmail.com
  github: ds3c-ctf-team
  twitter: ds3c-ctf-team
  pinterest: ds3c-ctf-team
  linkedin: ds3c-ctf-team
  bio: Ds3c CTF FROM MONGOLIA
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
